apiVersion: maestro/v1alpha1
kind: Workflow
metadata:
  name: meta_agent_workflow
  labels:
    project: maestro-demo
spec:
  template:
    metadata:
      name: meta_agent_workflow
      labels:
        project: maestro-demo
    agents:
      - NLP Agent Planner V2
      - Format Input Agent V2
      - Create Agent YAML V2
      - markdown formatter
      - tagger agent
    prompt: I want to compare the current weather with the historical averages. To do this, I probably will need 2 agents, one to retrieve the weather and one to compare to the historical average.
    steps:
      - name: English Instructions to Prompt
        agent: NLP Agent Planner V2
      - name: Specify Agents for Agent Generation
        agent: Format Input Agent V2
      - name: Creating Agent YAML Workflow
        agent: Create Agent YAML V2
      - name: Readable output
        agent: markdown formatter
      - name: add tags
        agent: tagger agent